-- Generated by saronite-bot/cmd/phasegen. Do not edit.
-- Stat weights (EP) per wowsims simulator; see the bot's internal/gear/analysis/weights.go.
local _, ns = ...
ns.Data = ns.Data or { phases = {} }
ns.Data.phases = ns.Data.phases or {}

ns.Data.weights = {
	["balance_druid"] = { CRIT = 0.75, HASTE = 0.85, INT = 0.43, MP5 = 0, SP = 1, SPI = 0.34 },
	["deathknight"] = { AGI = 0.62, AP = 1, ARMOR = 0.01, ARP = 0.77, CRIT = 1, EXP = 1.6, HASTE = 0.9, HIT = 1.92, MHDPS = 3.1, OHDPS = 1.79, STR = 3.22 },
	["elemental_shaman"] = { CRIT = 0.67, HASTE = 0.9, INT = 0.22, MP5 = 0.08, SP = 1 },
	["enhancement_shaman"] = { AGI = 1.59, AP = 1, ARP = 0.48, CRIT = 0.81, EXP = 0, HASTE = 1.61, HIT = 1.38, INT = 1.1, MHDPS = 5.21, OHDPS = 2.21, SP = 1.13, STR = 1.1 },
	["feral_druid"] = { AGI = 2.39, AP = 1, ARP = 2.08, CRIT = 2.23, EXP = 2.44, FAP = 1, HASTE = 1.83, HIT = 2.51, MHDPS = 16.5, STR = 2.4 },
	["feral_tank_druid"] = { AGI = 4.4974, AP = 1, ARMOR = 3.5665, ARP = 1.584, CRIT = 1.5143, DEF = 1.8171, DODGE = 2.0196, EXP = 2.6597, FAP = 1, HASTE = 2.0983, HIT = 2.9282, HP = 0.4465, MHDPS = 0, STA = 7.3021, STR = 2.3786 },
	["healing_priest"] = { CRIT = 0.6, HASTE = 0.9, INT = 0.7, MP5 = 0.45, SP = 1, SPI = 0.55 },
	["holy_paladin"] = { CRIT = 0.6, HASTE = 1.05, INT = 1.25, MP5 = 0.95, SP = 1 },
	["hunter"] = { AGI = 2.65, AP = 1, ARP = 1.32, CRIT = 1.5, HASTE = 1.39, HIT = 2, INT = 0.5, RDPS = 6.32, STA = 0.1 },
	["mage"] = { CRIT = 0.58, HASTE = 0.94, HIT = 0.38, INT = 0.48, MP5 = 0.09, SP = 1, SPI = 0.42 },
	["protection_paladin"] = { AGI = 0.38, AP = 0.05, ARMOR = 0.06, ARP = 0.03, BLOCK = 0.6, BLOCKV = 0.45, CRIT = 0.2, DEF = 0.6, DODGE = 0.6, EXP = 0.75, HASTE = 0.12, HIT = 0.8, MHDPS = 1.5, PARRY = 0.55, SP = 0.12, STA = 1, STR = 0.5 },
	["protection_warrior"] = { AGI = 0.38, AP = 0.05, ARMOR = 0.07, ARP = 0.1, BLOCK = 0.65, BLOCKV = 0.45, CRIT = 0.2, DEF = 0.6, DODGE = 0.62, EXP = 0.75, HASTE = 0.1, HIT = 0.8, MHDPS = 1.5, PARRY = 0.58, STA = 1, STR = 0.45 },
	["restoration_druid"] = { CRIT = 0.35, HASTE = 0.95, INT = 0.45, MP5 = 0.5, SP = 1, SPI = 0.7 },
	["restoration_shaman"] = { CRIT = 0.6, HASTE = 0.85, INT = 0.85, MP5 = 0.6, SP = 1 },
	["retribution_paladin"] = { AGI = 1.13, AP = 1, ARP = 0.76, CRIT = 1.16, EXP = 1.8, HASTE = 0.95, HIT = 1.96, INT = 0.15, MHDPS = 7.33, MP5 = 0.05, SP = 0.32, STR = 2.53 },
	["rogue"] = { AGI = 1.86, AP = 1, ARP = 0.84, CRIT = 1.2, EXP = 1.9, HASTE = 1.3, HIT = 1.39, MHDPS = 2.94, OHDPS = 2.45, STR = 1.1 },
	["shadow_priest"] = { CRIT = 0.74, HASTE = 0.95, HIT = 0.87, INT = 0.11, MP5 = 0, SP = 1, SPI = 0.47 },
	["smite_priest"] = { CRIT = 0.32, HASTE = 0.78, HIT = 1.65, INT = 0.38, MP5 = 0.35, SP = 1, SPI = 0.38 },
	["tank_deathknight"] = { AGI = 0.35, AP = 0.04, ARMOR = 0.05, ARP = 0.1, CRIT = 0.15, DEF = 0.55, DODGE = 0.6, EXP = 0.75, HASTE = 0.12, HIT = 0.8, MHDPS = 1.5, OHDPS = 0, PARRY = 0.62, STA = 1, STR = 0.4 },
	["warlock"] = { CRIT = 0.55, HASTE = 0.81, HIT = 0.93, INT = 0.18, SP = 1, SPI = 0.45, STA = 0.01 },
	["warrior"] = { AGI = 1.82, AP = 1, ARMOR = 0.03, ARP = 2.17, CRIT = 2.12, EXP = 2.55, HASTE = 1.4, HIT = 0.79, MHDPS = 6.29, OHDPS = 3.58, STR = 2.72 },
}
