-- Generated by saronite-bot/cmd/phasegen. Do not edit.
-- Stat weights (EP) per wowsims simulator; see the bot's internal/gear/analysis/weights.go.
local _, ns = ...
ns.Data = ns.Data or { phases = {} }
ns.Data.phases = ns.Data.phases or {}

ns.Data.weights = {
	["balance_druid"] = { CRIT = 0.82, HASTE = 0.8, INT = 0.43, MP5 = 0, SP = 1, SPI = 0.34 },
	["deathknight"] = { AGI = 0.62, AP = 1, ARMOR = 0.01, ARP = 0.77, CRIT = 0.76, EXP = 1.13, HASTE = 1.85, HIT = 1.92, MHDPS = 3.1, OHDPS = 1.79, STR = 3.22 },
	["elemental_shaman"] = { CRIT = 0.67, HASTE = 1.29, INT = 0.22, MP5 = 0.08, SP = 1 },
	["enhancement_shaman"] = { AGI = 1.59, AP = 1, ARP = 0.48, CRIT = 0.81, EXP = 0, HASTE = 1.61, HIT = 1.38, INT = 1.48, MHDPS = 5.21, OHDPS = 2.21, SP = 1.13, STR = 1.1 },
	["feral_druid"] = { AGI = 2.39, AP = 1, ARP = 2.08, CRIT = 2.23, EXP = 2.44, FAP = 1, HASTE = 1.83, HIT = 2.51, MHDPS = 16.5, STR = 2.4 },
	["feral_tank_druid"] = { AGI = 4.4974, AP = 1, ARMOR = 3.5665, ARP = 1.584, CRIT = 1.5143, DEF = 1.8171, DODGE = 2.0196, EXP = 2.6597, FAP = 1, HASTE = 2.0983, HIT = 2.9282, HP = 0.4465, MHDPS = 0, STA = 7.3021, STR = 2.3786 },
	["healing_priest"] = { CRIT = 0.55, HASTE = 0.6, INT = 0.65, MP5 = 0.7, SP = 1, SPI = 0.5 },
	["holy_paladin"] = { CRIT = 0.65, HASTE = 0.55, INT = 0.95, MP5 = 1.1, SP = 1 },
	["hunter"] = { AGI = 2.65, AP = 1, ARP = 1.32, CRIT = 1.5, HASTE = 1.39, HIT = 2, INT = 1.1, RDPS = 6.32, STA = 0.5 },
	["mage"] = { CRIT = 0.58, HASTE = 0.94, HIT = 0.38, INT = 0.48, MP5 = 0.09, SP = 1, SPI = 0.42 },
	["protection_paladin"] = { AGI = 0.62, AP = 0.26, ARMOR = 0.07, ARP = 0.04, BLOCK = 0.52, BLOCKV = 0.28, CRIT = 0.3, DEF = 0.54, DODGE = 0.46, EXP = 0.69, HASTE = 0.17, HIT = 0.79, MHDPS = 3.33, PARRY = 0.61, SP = 0.13, STA = 1.14, STR = 1 },
	["protection_warrior"] = { AGI = 2.771, AP = 0.32, ARMOR = 0.174, ARP = 1.055, BLOCK = 1.32, BLOCKV = 1.373, CRIT = 0.925, DEF = 3.305, DODGE = 2.606, EXP = 1.44, HASTE = 0.431, HIT = 1.432, MHDPS = 6.081, PARRY = 2.649, STA = 2.336, STR = 1.555 },
	["restoration_druid"] = { CRIT = 0.25, HASTE = 0.95, INT = 0.45, MP5 = 0.6, SP = 1, SPI = 0.6 },
	["restoration_shaman"] = { CRIT = 0.55, HASTE = 0.85, INT = 0.6, MP5 = 0.9, SP = 1 },
	["retribution_paladin"] = { AGI = 1.13, AP = 1, ARP = 0.76, CRIT = 1.16, EXP = 1.8, HASTE = 1.44, HIT = 1.96, INT = 0.15, MHDPS = 7.33, MP5 = 0.05, SP = 0.32, STR = 2.53 },
	["rogue"] = { AGI = 1.86, AP = 1, ARP = 0.84, CRIT = 1.32, EXP = 0.98, HASTE = 1.48, HIT = 1.39, MHDPS = 2.94, OHDPS = 2.45, STR = 1.14 },
	["shadow_priest"] = { CRIT = 0.74, HASTE = 1.65, HIT = 0.87, INT = 0.11, MP5 = 0, SP = 1, SPI = 0.47 },
	["smite_priest"] = { CRIT = 0.32, HASTE = 0.78, HIT = 1.65, INT = 0.38, MP5 = 0.35, SP = 1, SPI = 0.38 },
	["tank_deathknight"] = { AGI = 0.6, AP = 0.06, ARMOR = 0.05, ARP = 0.19, BLOCK = 0.35, BLOCKV = 0.59, CRIT = 0.28, DEF = 0.8, DODGE = 0.7, EXP = 0.67, HASTE = 0.21, HIT = 0.67, MHDPS = 3.1, OHDPS = 0, PARRY = 0.58, STA = 1, STR = 0.33 },
	["warlock"] = { CRIT = 0.53, HASTE = 0.81, HIT = 0.93, INT = 0.18, SP = 1, SPI = 0.54, STA = 0.01 },
	["warrior"] = { AGI = 1.82, AP = 1, ARMOR = 0.03, ARP = 2.17, CRIT = 2.12, EXP = 2.55, HASTE = 1.72, HIT = 0.79, MHDPS = 6.29, OHDPS = 3.58, STR = 2.72 },
}
